# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=100)),
                ('first_timestamp', models.DateTimeField(default=None, null=True)),
                ('last_timestamp', models.DateTimeField(default=None, null=True)),
                ('last_time_used', models.DateTimeField(default=None, null=True)),
                ('total_foreground_time', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternetLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('url', models.CharField(default=None, max_length=40)),
                ('logs', models.CharField(default=None, max_length=40)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('unique_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='applogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sngc_visualization.User'),
        ),
    ]
