# Generated by Django 2.0.5 on 2018-05-07 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
