# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sngc_visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogs',
            name='total_foreground_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
