# Generated by Django 2.0.5 on 2018-05-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sngc_visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='percentage',
            field=models.FloatField(default=None, null=True),
        ),
    ]
