# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 05:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sngc_visualization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applogs',
            old_name='timeline',
            new_name='total_foreground_time',
        ),
        migrations.RemoveField(
            model_name='applogs',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='applogs',
            name='logs',
        ),
        migrations.AddField(
            model_name='applogs',
            name='App_name',
            field=models.CharField(default=datetime.datetime(2017, 9, 27, 5, 4, 53, 903067), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applogs',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applogs',
            name='last_used_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
