# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sngc_visualization', '0002_auto_20170927_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applogs',
            old_name='App_name',
            new_name='app_name',
        ),
        migrations.RenameField(
            model_name='applogs',
            old_name='last_used_time',
            new_name='first_timestamp',
        ),
        migrations.AddField(
            model_name='applogs',
            name='last_time_used',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='applogs',
            name='last_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
