# Generated by Django 2.0.5 on 2018-05-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sngc_visualization', '0002_alert_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='percentage',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
