# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sngc_visualization', '0003_auto_20170927_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('unique_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='applogs',
            name='user',
            field=models.ForeignKey(default='dsa', on_delete=django.db.models.deletion.CASCADE, to='sngc_visualization.User'),
            preserve_default=False,
        ),
    ]
